"""Talaria's built-in themes.

The first four values are copied verbatim from the integrated visual
specification dated 2026-08-30.  Keeping the built-ins as Python constants
makes them unambiguous wheel content and gives the issue #105 importer a
stable fallback source.
"""

from __future__ import annotations

from talaria.themes import ThemeSpec

REFINED_DEFAULT = ThemeSpec(
    slug="refined-default",
    name="Refined Default",
    dark=False,
    tokens={
        "talaria.canvas": "#F6F8FA",
        "talaria.surface": "#FFFFFF",
        "talaria.panel": "#EAEFF4",
        "talaria.text": "#1F2328",
        "talaria.text.muted": "#57606A",
        "talaria.primary": "#0969DA",
        "talaria.secondary": "#6F42C1",
        "talaria.accent": "#087F5B",
        "talaria.success": "#1A7F37",
        "talaria.warning": "#8A5A00",
        "talaria.error": "#CF222E",
        "talaria.border": "#6E7781",
        "talaria.border.muted": "#7D8590",
        "talaria.focus": "#0969DA",
        "talaria.selection.background": "#0969DA",
        "talaria.selection.text": "#FFFFFF",
        "talaria.status.background": "#24292F",
        "talaria.status.text": "#F6F8FA",
        "talaria.status.muted": "#C6CDD5",
        "talaria.status.separator": "#8C959F",
        "talaria.status.success": "#3FB950",
        "talaria.status.warning": "#D29922",
        "talaria.status.error": "#FF7B72",
        "talaria.status.attention": "#58A6FF",
        "talaria.inspector.background": "#FFFFFF",
        "talaria.inspector.border": "#6E7781",
        "talaria.inspector.heading": "#0969DA",
        "talaria.transcript.operator": "#0969DA",
        "talaria.transcript.operator.background": "#EAF2FC",
        "talaria.transcript.assistant": "#1A7F37",
        "talaria.transcript.assistant.background": "#EAF7ED",
        "talaria.transcript.reasoning": "#6F42C1",
        "talaria.transcript.reasoning.background": "#F1EBFC",
        "talaria.transcript.activity": "#0B7285",
        "talaria.transcript.activity.background": "#E7F5F7",
        "talaria.transcript.session": "#57606A",
        "talaria.transcript.session.background": "#EEF1F4",
        "talaria.transcript.fault": "#CF222E",
        "talaria.transcript.fault.background": "#FDEDEF",
        "talaria.diff.context": "#1F2328",
        "talaria.diff.line-number": "#57606A",
        "talaria.diff.added": "#116329",
        "talaria.diff.added.background": "#E6F4EA",
        "talaria.diff.removed": "#A40E26",
        "talaria.diff.removed.background": "#FCE8E6",
        "talaria.diff.hunk": "#0550AE",
        "talaria.diff.hunk.background": "#EAF2FC",
        "talaria.diff.intraline-added.background": "#BFE3C8",
        "talaria.diff.intraline-removed.background": "#F4C7C3",
        "talaria.syntax.comment": "#57606A",
        "talaria.syntax.keyword": "#6F42C1",
        "talaria.syntax.string": "#116329",
        "talaria.syntax.number": "#953800",
        "talaria.syntax.function": "#0550AE",
        "talaria.syntax.type": "#0B7285",
        "talaria.syntax.variable": "#1F2328",
        "talaria.syntax.operator": "#6F42C1",
        "talaria.syntax.constant": "#A40E4C",
    },
)

DARK_GREEN_TERMINAL = ThemeSpec(
    slug="dark-green-terminal",
    name="Dark Green Terminal",
    dark=True,
    tokens={
        "talaria.canvas": "#07110B",
        "talaria.surface": "#0B1A10",
        "talaria.panel": "#102418",
        "talaria.text": "#D6F5DC",
        "talaria.text.muted": "#8FB99A",
        "talaria.primary": "#6EE7A0",
        "talaria.secondary": "#9BD4A7",
        "talaria.accent": "#39FF88",
        "talaria.success": "#6EE7A0",
        "talaria.warning": "#FFD166",
        "talaria.error": "#FF7B72",
        "talaria.border": "#4BAA6A",
        "talaria.border.muted": "#337A4B",
        "talaria.focus": "#39FF88",
        "talaria.selection.background": "#39FF88",
        "talaria.selection.text": "#041008",
        "talaria.status.background": "#020703",
        "talaria.status.text": "#D6F5DC",
        "talaria.status.muted": "#8FB99A",
        "talaria.status.separator": "#4BAA6A",
        "talaria.status.success": "#6EE7A0",
        "talaria.status.warning": "#FFD166",
        "talaria.status.error": "#FF7B72",
        "talaria.status.attention": "#39FF88",
        "talaria.inspector.background": "#0B1A10",
        "talaria.inspector.border": "#4BAA6A",
        "talaria.inspector.heading": "#6EE7A0",
        "talaria.transcript.operator": "#7EE7A5",
        "talaria.transcript.operator.background": "#0E2216",
        "talaria.transcript.assistant": "#6EE7A0",
        "talaria.transcript.assistant.background": "#0D2617",
        "talaria.transcript.reasoning": "#B4D6A0",
        "talaria.transcript.reasoning.background": "#162518",
        "talaria.transcript.activity": "#72D6B1",
        "talaria.transcript.activity.background": "#0E241B",
        "talaria.transcript.session": "#A8C5AE",
        "talaria.transcript.session.background": "#142018",
        "talaria.transcript.fault": "#FF8A80",
        "talaria.transcript.fault.background": "#281313",
        "talaria.diff.context": "#D6F5DC",
        "talaria.diff.line-number": "#8FB99A",
        "talaria.diff.added": "#8BF0A8",
        "talaria.diff.added.background": "#0E2A18",
        "talaria.diff.removed": "#FF9A91",
        "talaria.diff.removed.background": "#2A1412",
        "talaria.diff.hunk": "#8FD3FF",
        "talaria.diff.hunk.background": "#102631",
        "talaria.diff.intraline-added.background": "#1B5A31",
        "talaria.diff.intraline-removed.background": "#6B2520",
        "talaria.syntax.comment": "#8FB99A",
        "talaria.syntax.keyword": "#B6F09C",
        "talaria.syntax.string": "#8BE9A8",
        "talaria.syntax.number": "#FFD166",
        "talaria.syntax.function": "#7DD3FC",
        "talaria.syntax.type": "#A7E3C1",
        "talaria.syntax.variable": "#D6F5DC",
        "talaria.syntax.operator": "#B4D6A0",
        "talaria.syntax.constant": "#FFB86C",
    },
)

NEUTRAL_DARK = ThemeSpec(
    slug="neutral-dark",
    name="Neutral Dark",
    dark=True,
    tokens={
        "talaria.canvas": "#151719",
        "talaria.surface": "#1D2023",
        "talaria.panel": "#25292D",
        "talaria.text": "#E6E9EC",
        "talaria.text.muted": "#A6ADB4",
        "talaria.primary": "#8AB4F8",
        "talaria.secondary": "#C4A7E7",
        "talaria.accent": "#9AB7D3",
        "talaria.success": "#82C99A",
        "talaria.warning": "#E4C07A",
        "talaria.error": "#F08C8C",
        "talaria.border": "#7A838C",
        "talaria.border.muted": "#707983",
        "talaria.focus": "#B3C7DB",
        "talaria.selection.background": "#B3C7DB",
        "talaria.selection.text": "#101214",
        "talaria.status.background": "#0D0F10",
        "talaria.status.text": "#E6E9EC",
        "talaria.status.muted": "#A6ADB4",
        "talaria.status.separator": "#68717A",
        "talaria.status.success": "#82C99A",
        "talaria.status.warning": "#E4C07A",
        "talaria.status.error": "#F08C8C",
        "talaria.status.attention": "#9AB7D3",
        "talaria.inspector.background": "#1D2023",
        "talaria.inspector.border": "#68717A",
        "talaria.inspector.heading": "#B3C7DB",
        "talaria.transcript.operator": "#8AB4F8",
        "talaria.transcript.operator.background": "#1A2430",
        "talaria.transcript.assistant": "#82C99A",
        "talaria.transcript.assistant.background": "#1A2920",
        "talaria.transcript.reasoning": "#C4A7E7",
        "talaria.transcript.reasoning.background": "#282133",
        "talaria.transcript.activity": "#8EC5C5",
        "talaria.transcript.activity.background": "#1B2929",
        "talaria.transcript.session": "#A6ADB4",
        "talaria.transcript.session.background": "#24272A",
        "talaria.transcript.fault": "#F08C8C",
        "talaria.transcript.fault.background": "#321D1D",
        "talaria.diff.context": "#E6E9EC",
        "talaria.diff.line-number": "#A6ADB4",
        "talaria.diff.added": "#9AD5AA",
        "talaria.diff.added.background": "#1B2B20",
        "talaria.diff.removed": "#F2A0A0",
        "talaria.diff.removed.background": "#321F1F",
        "talaria.diff.hunk": "#9EC5F8",
        "talaria.diff.hunk.background": "#1B2735",
        "talaria.diff.intraline-added.background": "#285137",
        "talaria.diff.intraline-removed.background": "#643333",
        "talaria.syntax.comment": "#A6ADB4",
        "talaria.syntax.keyword": "#C4A7E7",
        "talaria.syntax.string": "#9AD5AA",
        "talaria.syntax.number": "#E4C07A",
        "talaria.syntax.function": "#8AB4F8",
        "talaria.syntax.type": "#8EC5C5",
        "talaria.syntax.variable": "#E6E9EC",
        "talaria.syntax.operator": "#B9C0C7",
        "talaria.syntax.constant": "#F2B37C",
    },
)

ACCESSIBLE_HIGH_CONTRAST = ThemeSpec(
    slug="accessible-high-contrast",
    name="Accessible High Contrast",
    dark=True,
    tokens={
        "talaria.canvas": "#000000",
        "talaria.surface": "#0A0A0A",
        "talaria.panel": "#141414",
        "talaria.text": "#FFFFFF",
        "talaria.text.muted": "#D6D6D6",
        "talaria.primary": "#66B3FF",
        "talaria.secondary": "#D7A9FF",
        "talaria.accent": "#00FF85",
        "talaria.success": "#63FF90",
        "talaria.warning": "#FFD75F",
        "talaria.error": "#FF6B6B",
        "talaria.border": "#FFFFFF",
        "talaria.border.muted": "#8A8A8A",
        "talaria.focus": "#00FFFF",
        "talaria.selection.background": "#FFFF00",
        "talaria.selection.text": "#000000",
        "talaria.status.background": "#000000",
        "talaria.status.text": "#FFFFFF",
        "talaria.status.muted": "#D6D6D6",
        "talaria.status.separator": "#FFFFFF",
        "talaria.status.success": "#63FF90",
        "talaria.status.warning": "#FFD75F",
        "talaria.status.error": "#FF6B6B",
        "talaria.status.attention": "#00FF85",
        "talaria.inspector.background": "#0A0A0A",
        "talaria.inspector.border": "#FFFFFF",
        "talaria.inspector.heading": "#00FFFF",
        "talaria.transcript.operator": "#66B3FF",
        "talaria.transcript.operator.background": "#00172B",
        "talaria.transcript.assistant": "#63FF90",
        "talaria.transcript.assistant.background": "#00210C",
        "talaria.transcript.reasoning": "#D7A9FF",
        "talaria.transcript.reasoning.background": "#1D0B2B",
        "talaria.transcript.activity": "#5CFFF1",
        "talaria.transcript.activity.background": "#002522",
        "talaria.transcript.session": "#E0E0E0",
        "talaria.transcript.session.background": "#1A1A1A",
        "talaria.transcript.fault": "#FF7B7B",
        "talaria.transcript.fault.background": "#2A0000",
        "talaria.diff.context": "#FFFFFF",
        "talaria.diff.line-number": "#D6D6D6",
        "talaria.diff.added": "#9BFFB5",
        "talaria.diff.added.background": "#003313",
        "talaria.diff.removed": "#FF9A9A",
        "talaria.diff.removed.background": "#3A0000",
        "talaria.diff.hunk": "#8FD3FF",
        "talaria.diff.hunk.background": "#002744",
        "talaria.diff.intraline-added.background": "#005C24",
        "talaria.diff.intraline-removed.background": "#6E0000",
        "talaria.syntax.comment": "#D6D6D6",
        "talaria.syntax.keyword": "#D7A9FF",
        "talaria.syntax.string": "#9BFFB5",
        "talaria.syntax.number": "#FFD75F",
        "talaria.syntax.function": "#8FD3FF",
        "talaria.syntax.type": "#5CFFF1",
        "talaria.syntax.variable": "#FFFFFF",
        "talaria.syntax.operator": "#F2F2F2",
        "talaria.syntax.constant": "#FFB86B",
    },
)

#: Homebrew (issue #123): the fifth built-in, a restrained green-black theme
#: for operators who live in green-tinted terminals but find
#: :data:`DARK_GREEN_TERMINAL`'s neon accents fatiguing. Provenance: designed
#: for Talaria v0.6.0, not sampled from any host terminal palette — every
#: value below was chosen in this file and measured against the same floors
#: the visual specification pins for the first four themes (body pairings at
#: 4.5 or better, component pairings at 3.0 or better; the transcript
#: category triples hold 9.2 or better on text and 5.7 or better on markers).
#: Mapping: the canvas/surface/panel/text/border/selection/status families
#: are flat chrome a terminal palette could equally describe, while the
#: transcript, diff, and syntax families are Talaria-semantic and stay
#: Talaria-owned per decision C. The per-category body tints ride the groups
#: layer (``talaria.text`` reinterpreted per category) so the shared body
#: text remains the one value an override replaces wholesale. Homebrew is
#: registered beside the other built-ins but is never the startup default.
HOMEBREW = ThemeSpec(
    slug="homebrew",
    name="Homebrew",
    dark=True,
    description=(
        "Talaria-designed green-black palette (v0.6.0) — not sampled "
        "from a host terminal, not the Homebrew package manager"
    ),
    tokens={
        "talaria.canvas": "#050905",
        "talaria.surface": "#0A120D",
        "talaria.panel": "#0E1811",
        "talaria.text": "#C9D9CE",
        "talaria.text.muted": "#7E937F",
        "talaria.primary": "#6FA287",
        "talaria.secondary": "#8A9E7E",
        "talaria.accent": "#4E9A6A",
        "talaria.success": "#5FA86F",
        "talaria.warning": "#C9A44A",
        "talaria.error": "#D97B7B",
        "talaria.border": "#558F66",
        "talaria.border.muted": "#3B6B46",
        "talaria.focus": "#356B47",
        "talaria.selection.background": "#356B47",
        "talaria.selection.text": "#E8F2EA",
        "talaria.status.background": "#030604",
        "talaria.status.text": "#C9D9CE",
        "talaria.status.muted": "#7E937F",
        "talaria.status.separator": "#527F5E",
        "talaria.status.success": "#5FA86F",
        "talaria.status.warning": "#C9A44A",
        "talaria.status.error": "#D97B7B",
        "talaria.status.attention": "#4E9A6A",
        "talaria.inspector.background": "#0A120D",
        "talaria.inspector.border": "#558F66",
        "talaria.inspector.heading": "#6FA287",
        "talaria.transcript.operator": "#6FA287",
        "talaria.transcript.operator.background": "#0B1410",
        "talaria.transcript.assistant": "#5FA86F",
        "talaria.transcript.assistant.background": "#0A1310",
        "talaria.transcript.reasoning": "#8A9E7E",
        "talaria.transcript.reasoning.background": "#0D130E",
        "talaria.transcript.activity": "#5E9E8E",
        "talaria.transcript.activity.background": "#0A1210",
        "talaria.transcript.session": "#7E937F",
        "talaria.transcript.session.background": "#0C110D",
        "talaria.transcript.fault": "#D97B7B",
        "talaria.transcript.fault.background": "#160C0C",
        "talaria.diff.context": "#C9D9CE",
        "talaria.diff.line-number": "#7E937F",
        "talaria.diff.added": "#7CC496",
        "talaria.diff.added.background": "#0B1A10",
        "talaria.diff.removed": "#DE9A9A",
        "talaria.diff.removed.background": "#1A0E0E",
        "talaria.diff.hunk": "#7FA8B8",
        "talaria.diff.hunk.background": "#0A1418",
        "talaria.diff.intraline-added.background": "#1E4A2E",
        "talaria.diff.intraline-removed.background": "#5A2323",
        "talaria.syntax.comment": "#7E937F",
        "talaria.syntax.keyword": "#8FBF9B",
        "talaria.syntax.string": "#7CC496",
        "talaria.syntax.number": "#C9A44A",
        "talaria.syntax.function": "#7FA8B8",
        "talaria.syntax.type": "#6EAA9A",
        "talaria.syntax.variable": "#C9D9CE",
        "talaria.syntax.operator": "#8A9E7E",
        "talaria.syntax.constant": "#C99A6E",
    },
    groups={
        "operator": {"talaria.text": "#D4E2D8"},
        "assistant": {"talaria.text": "#C9D9CE"},
        "reasoning": {"talaria.text": "#BFCBBF"},
        "activity": {"talaria.text": "#C2D4CB"},
        "session": {"talaria.text": "#A9B8AC"},
        "fault": {"talaria.text": "#E3CFCF"},
    },
)

BUILTIN_THEMES: tuple[ThemeSpec, ...] = (
    REFINED_DEFAULT,
    DARK_GREEN_TERMINAL,
    NEUTRAL_DARK,
    ACCESSIBLE_HIGH_CONTRAST,
    HOMEBREW,
)

__all__ = [
    "ACCESSIBLE_HIGH_CONTRAST",
    "BUILTIN_THEMES",
    "DARK_GREEN_TERMINAL",
    "HOMEBREW",
    "NEUTRAL_DARK",
    "REFINED_DEFAULT",
]
